/**
 * affix-taxonomy.ts
 * Structural categorization of affixes as game-mechanical facts.
 * Tells the compiler which affixes are class-gated, utility-only,
 * or mastery-signature affixes that need special treatment.
 *
 * This is NOT weight data. Weights come from the knowledge base.
 * This is metadata about what KIND of affix something is.
 *
 * AUTO-GENERATED by update-taxonomy.py — do not edit by hand.
 * Re-run the script to reconcile against MasterAffixesList.json.
 */

import type { BaseClass, Mastery } from './classes';

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

/** Structural category — not the same as weight category (essential/strong/etc.) */
export type AffixStructuralCategory =
  | 'universal_defensive'   // health, resistances — every build wants these
  | 'universal_utility'     // movement speed, mana, cooldown recovery
  | 'class_gated'           // only valid for specific classes
  | 'mastery_signature'     // strongly associated with one mastery
  | 'attack_only'           // melee/attack builds only
  | 'spell_only'            // caster builds only
  | 'minion_only'           // minion builds only
  | 'general_offensive';    // offensive affixes with no attack-type restriction

export interface AffixTaxonomyEntry {
  readonly affixId: number;
  readonly affixName: string;
  readonly structuralCategory: AffixStructuralCategory;
  /** If class_gated, which base classes can benefit */
  readonly validClasses?: readonly BaseClass[];
  /** If mastery_signature, which masteries this is most associated with */
  readonly signatureMasteries?: readonly Mastery[];
}

// ─────────────────────────────────────────────
// Taxonomy Entries
// ─────────────────────────────────────────────

export const AFFIX_TAXONOMY: readonly AffixTaxonomyEntry[] = [

  // ── Universal Defensive ─────────────────────────────────

  { affixId:   31, affixName: 'Added Armor', structuralCategory: 'universal_defensive' },
  { affixId:    3, affixName: 'Added Block Chance', structuralCategory: 'universal_defensive' },
  { affixId:   81, affixName: 'Added Block Effectiveness', structuralCategory: 'universal_defensive' },
  { affixId:    8, affixName: 'Added Dodge Rating', structuralCategory: 'universal_defensive' },
  { affixId:   25, affixName: 'Added Health', structuralCategory: 'universal_defensive' },
  { affixId:   51, affixName: 'Added Stun Avoidance', structuralCategory: 'universal_defensive' },
  { affixId:   46, affixName: 'All Resistances', structuralCategory: 'universal_defensive' },
  { affixId:   17, affixName: 'Cold Resistance', structuralCategory: 'universal_defensive' },
  { affixId:   80, affixName: 'Elemental Resistance', structuralCategory: 'universal_defensive' },
  { affixId:   92, affixName: 'Endurance', structuralCategory: 'universal_defensive' },
  { affixId:  425, affixName: 'Endurance Threshold', structuralCategory: 'universal_defensive' },
  { affixId:   13, affixName: 'Fire Resistance', structuralCategory: 'universal_defensive' },
  { affixId:   41, affixName: 'Health Gained on Block', structuralCategory: 'universal_defensive' },
  { affixId:   20, affixName: 'Health On Kill', structuralCategory: 'universal_defensive' },
  { affixId:   90, affixName: 'Health Regen', structuralCategory: 'universal_defensive' },
  { affixId:    1, affixName: 'Increased Armor', structuralCategory: 'universal_defensive' },
  { affixId:   59, affixName: 'Increased Dodge Rating', structuralCategory: 'universal_defensive' },
  { affixId:   43, affixName: 'Increased Healing Effectiveness', structuralCategory: 'universal_defensive' },
  { affixId:   52, affixName: 'Increased Health', structuralCategory: 'universal_defensive' },
  { affixId:   22, affixName: 'Increased Health Regen', structuralCategory: 'universal_defensive' },
  { affixId:   74, affixName: 'Less Damage Taken on Block', structuralCategory: 'universal_defensive' },
  { affixId:   24, affixName: 'Lightning Resistance', structuralCategory: 'universal_defensive' },
  { affixId:   10, affixName: 'Necrotic Resistance', structuralCategory: 'universal_defensive' },
  { affixId:  717, affixName: 'Parry Chance', structuralCategory: 'universal_defensive' },
  { affixId:   45, affixName: 'Physical Resistance', structuralCategory: 'universal_defensive' },
  { affixId:   19, affixName: 'Poison Resistance', structuralCategory: 'universal_defensive' },
  { affixId:   83, affixName: 'Potion Health Converted to Ward', structuralCategory: 'universal_defensive' },
  { affixId:    7, affixName: 'Void Resistance', structuralCategory: 'universal_defensive' },
  { affixId:   99, affixName: 'Ward Gained on Kill', structuralCategory: 'universal_defensive' },

  // ── Universal Utility ───────────────────────────────────

  { affixId:   34, affixName: 'Added Mana', structuralCategory: 'universal_utility' },
  { affixId:   50, affixName: 'All Attributes', structuralCategory: 'universal_utility' },
  { affixId:  503, affixName: 'Dexterity', structuralCategory: 'universal_utility' },
  { affixId:   27, affixName: 'Increased Cooldown Recovery Speed', structuralCategory: 'universal_utility' },
  { affixId:  330, affixName: 'Increased Mana Regen', structuralCategory: 'universal_utility' },
  { affixId:   28, affixName: 'Increased Movement Speed', structuralCategory: 'universal_utility' },
  { affixId:   40, affixName: 'Leech Rate', structuralCategory: 'universal_utility' },
  { affixId:  505, affixName: 'Vitality', structuralCategory: 'universal_utility' },

  // ── Attack Only ─────────────────────────────────────────

  { affixId:  670, affixName: 'Added Bow Cold Damage', structuralCategory: 'attack_only' },
  { affixId:  434, affixName: 'Added Bow Fire Damage', structuralCategory: 'attack_only' },
  { affixId:  669, affixName: 'Added Bow Lightning Damage', structuralCategory: 'attack_only' },
  { affixId:  433, affixName: 'Added Bow Physical Damage', structuralCategory: 'attack_only' },
  { affixId:   78, affixName: 'Added Melee Cold Damage', structuralCategory: 'attack_only' },
  { affixId:   62, affixName: 'Added Melee Crit Chance', structuralCategory: 'attack_only' },
  { affixId:   77, affixName: 'Added Melee Fire Damage', structuralCategory: 'attack_only' },
  { affixId:   79, affixName: 'Added Melee Lightning Damage', structuralCategory: 'attack_only' },
  { affixId:   63, affixName: 'Added Melee Physical Damage', structuralCategory: 'attack_only' },
  { affixId:   76, affixName: 'Added Melee Void Damage', structuralCategory: 'attack_only' },
  { affixId:  671, affixName: 'Area for Melee Area Skills', structuralCategory: 'attack_only' },
  { affixId:   44, affixName: 'Health On Melee Hit', structuralCategory: 'attack_only' },
  { affixId:  432, affixName: 'Increased Bow Attack Speed', structuralCategory: 'attack_only' },
  { affixId:  431, affixName: 'Increased Bow Damage', structuralCategory: 'attack_only' },
  { affixId:    2, affixName: 'Increased Melee Attack Speed', structuralCategory: 'attack_only' },
  { affixId:   89, affixName: 'Increased Melee Damage', structuralCategory: 'attack_only' },
  { affixId:   91, affixName: 'Increased Melee Stun Chance', structuralCategory: 'attack_only' },
  { affixId:   87, affixName: 'Increased Throwing Attack Speed', structuralCategory: 'attack_only' },
  { affixId:  428, affixName: 'Melee Frailty Chance', structuralCategory: 'attack_only' },
  { affixId:   69, affixName: 'Melee Health Leech', structuralCategory: 'attack_only' },

  // ── Spell Only ──────────────────────────────────────────

  { affixId:   49, affixName: 'Added Spell Damage For Swords', structuralCategory: 'spell_only' },
  { affixId:  104, affixName: 'All Resistances While Channelling', structuralCategory: 'spell_only' },
  { affixId:  103, affixName: 'Damage While Channelling', structuralCategory: 'spell_only' },
  { affixId:    4, affixName: 'Increased Cast Speed', structuralCategory: 'spell_only' },
  { affixId:   84, affixName: 'Increased Spell Crit Chance', structuralCategory: 'spell_only' },
  { affixId:   38, affixName: 'Increased Spell Damage', structuralCategory: 'spell_only' },

  // ── Minion Only ─────────────────────────────────────────

  { affixId:   26, affixName: 'Increased Minion Damage', structuralCategory: 'minion_only' },
  { affixId:   98, affixName: 'Increased Minion Damage Over Time', structuralCategory: 'minion_only' },

  // ── General Offensive ───────────────────────────────────

  { affixId:    6, affixName: 'Added Critical Strike Multiplier', structuralCategory: 'general_offensive' },
  { affixId:   86, affixName: 'Armor Shred Chance', structuralCategory: 'general_offensive' },
  { affixId:  701, affixName: 'Avel\'s', structuralCategory: 'general_offensive' },
  { affixId:   60, affixName: 'Chance To Blind', structuralCategory: 'general_offensive' },
  { affixId:   56, affixName: 'Chance To Chill', structuralCategory: 'general_offensive' },
  { affixId:   47, affixName: 'Chance To Chill Attackers', structuralCategory: 'general_offensive' },
  { affixId:   55, affixName: 'Chance To Ignite', structuralCategory: 'general_offensive' },
  { affixId:   54, affixName: 'Chance To Poison', structuralCategory: 'general_offensive' },
  { affixId:   85, affixName: 'Chance To Shock', structuralCategory: 'general_offensive' },
  { affixId:   94, affixName: 'Chance To Shock Attackers', structuralCategory: 'general_offensive' },
  { affixId:   57, affixName: 'Chance To Slow', structuralCategory: 'general_offensive' },
  { affixId:   48, affixName: 'Chance To Slow Attackers', structuralCategory: 'general_offensive' },
  { affixId:   68, affixName: 'Chance to Inflict Bleed', structuralCategory: 'general_offensive' },
  { affixId:   35, affixName: 'Cold Penetration', structuralCategory: 'general_offensive' },
  { affixId:   32, affixName: 'Fire Penetration', structuralCategory: 'general_offensive' },
  { affixId:  429, affixName: 'Frailty Chance', structuralCategory: 'general_offensive' },
  { affixId:   11, affixName: 'Freeze Rate Multiplier', structuralCategory: 'general_offensive' },
  { affixId:  101, affixName: 'Increased Area for Area Skills', structuralCategory: 'general_offensive' },
  { affixId:   65, affixName: 'Increased Chance To Find Potions', structuralCategory: 'general_offensive' },
  { affixId:   16, affixName: 'Increased Cold Damage', structuralCategory: 'general_offensive' },
  { affixId:    5, affixName: 'Increased Critical Strike Chance', structuralCategory: 'general_offensive' },
  { affixId:   72, affixName: 'Increased Damage Over Time', structuralCategory: 'general_offensive' },
  { affixId:    9, affixName: 'Increased Elemental Damage', structuralCategory: 'general_offensive' },
  { affixId:  100, affixName: 'Increased Elemental Damage Over Time', structuralCategory: 'general_offensive' },
  { affixId:   12, affixName: 'Increased Fire Damage', structuralCategory: 'general_offensive' },
  { affixId:   23, affixName: 'Increased Lightning Damage', structuralCategory: 'general_offensive' },
  { affixId:   30, affixName: 'Increased Physical Damage', structuralCategory: 'general_offensive' },
  { affixId:   61, affixName: 'Increased Poison Damage', structuralCategory: 'general_offensive' },
  { affixId:   58, affixName: 'Increased Stun Chance', structuralCategory: 'general_offensive' },
  { affixId:  427, affixName: 'Less Bonus Damage Taken from Critical Strikes', structuralCategory: 'general_offensive' },
  { affixId:   39, affixName: 'Lightning Penetration', structuralCategory: 'general_offensive' },
  { affixId:   93, affixName: 'Necrotic Penetration', structuralCategory: 'general_offensive' },
  { affixId:   96, affixName: 'Percent Damage Reflected', structuralCategory: 'general_offensive' },
  { affixId:   33, affixName: 'Physical Penetration', structuralCategory: 'general_offensive' },
  { affixId:   37, affixName: 'Poison Penetration', structuralCategory: 'general_offensive' },
  { affixId:   95, affixName: 'Thorns', structuralCategory: 'general_offensive' },
  { affixId:    0, affixName: 'Void Penetration', structuralCategory: 'general_offensive' },

  // ── Class Gated ─────────────────────────────────────────

  {
    affixId: 749,
    affixName: 'Acolyte Added Spell Damage for Curses',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 747,
    affixName: 'Acolyte Additional Projectile Chance with Chaos Bolts',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 421,
    affixName: 'Acolyte Chance To Apply Damned On Hit',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 435,
    affixName: 'Acolyte Chance To Cast Marrow Shards When You Cast Transplant',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 415,
    affixName: 'Acolyte Chance To Gain 20 Ward On Kill With Hungering Souls',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 422,
    affixName: 'Acolyte Damage Leeched As Health While Transformed',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 410,
    affixName: 'Acolyte Increased Skeletal Mage Damage',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 748,
    affixName: 'Acolyte Increased Spirit Frequency with Chthonic Fissure',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 412,
    affixName: 'Acolyte Leech With Harvest',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 411,
    affixName: 'Acolyte Mana Gained On Harvest Use',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 384,
    affixName: 'Acolyte Minion Freeze Rate',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 413,
    affixName: 'Acolyte Minion Reflect',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 402,
    affixName: 'Acolyte Necrotic Damage While Transformed',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 401,
    affixName: 'Acolyte Physical Damage While Transformed',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 424,
    affixName: 'Acolyte Physical Spell Critical Strike Chance',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 423,
    affixName: 'Acolyte Reduced Health Cost Of Spells',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 420,
    affixName: 'Acolyte Spell Damage Per Skeletal Mage',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 88,
    affixName: 'Added Throwing Damage',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel', 'rogue'],
  },
  {
    affixId: 504,
    affixName: 'Attunement',
    structuralCategory: 'class_gated',
    validClasses: ['primalist', 'sentinel'],
  },
  {
    affixId: 53,
    affixName: 'Damage Dealt To Mana',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 341,
    affixName: 'Freeze Rate Per Stack of Chill',
    structuralCategory: 'class_gated',
    validClasses: ['primalist', 'mage'],
  },
  {
    affixId: 331,
    affixName: 'Increased Mana',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel', 'rogue'],
  },
  {
    affixId: 18,
    affixName: 'Increased Necrotic Damage',
    structuralCategory: 'class_gated',
    validClasses: ['acolyte'],
  },
  {
    affixId: 15,
    affixName: 'Increased Void Damage',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 502,
    affixName: 'Intelligence',
    structuralCategory: 'class_gated',
    validClasses: ['mage', 'acolyte'],
  },
  {
    affixId: 383,
    affixName: 'Mage Added Spell Damage While Channelling',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 387,
    affixName: 'Mage Chance To Apply Frostbite With Cold Skills',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 393,
    affixName: 'Mage Chance To Cast Fire Aura On Crit',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 398,
    affixName: 'Mage Chance To Cast Fire Aura On Kill With A Fire Skill',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 396,
    affixName: 'Mage Chance To Cast Fire Aura When Hit',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 395,
    affixName: 'Mage Chance To Gain Lightning Aegis When Hit',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 391,
    affixName: 'Mage Chance To Ignite With Fire Skills',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 392,
    affixName: 'Mage Chance To Shock With Lightning Skills',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 399,
    affixName: 'Mage Chance to Apply a Spark Charge on Melee Hit',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 339,
    affixName: 'Mage Cold Penetration With Frostbite',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 688,
    affixName: 'Mage Flame Rush Speed',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 388,
    affixName: 'Mage Increased Cold Damage Over Time',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 394,
    affixName: 'Mage Increased Fire Aura Damage',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 389,
    affixName: 'Mage Increased Fire Damage Over Time',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 390,
    affixName: 'Mage Increased Melee Elemental Damage',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 385,
    affixName: 'Mage Lightning Crit Multi',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 400,
    affixName: 'Mage Mana Spent Gained as Ward',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 690,
    affixName: 'Mage Mana on Runebolt or Fireball Cast',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 381,
    affixName: 'Mage Spell Crit Doubled Over 300 Max Mana',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 386,
    affixName: 'Mage Spell Damage Leeched While Channelling',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 691,
    affixName: 'Mage Ward per Rune consumed with Runic Invocation',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 687,
    affixName: 'Mage Ward per Second on Glyph of Dominion',
    structuralCategory: 'class_gated',
    validClasses: ['mage'],
  },
  {
    affixId: 71,
    affixName: 'Minion Dodge Rating',
    structuralCategory: 'class_gated',
    validClasses: ['primalist', 'acolyte'],
  },
  {
    affixId: 70,
    affixName: 'Minion Health',
    structuralCategory: 'class_gated',
    validClasses: ['primalist', 'acolyte'],
  },
  {
    affixId: 73,
    affixName: 'Minion Health Regen',
    structuralCategory: 'class_gated',
    validClasses: ['primalist', 'acolyte'],
  },
  {
    affixId: 21,
    affixName: 'Primalist Added Spell Damage With Tempest Strike',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 663,
    affixName: 'Primalist Armor Shred Chance for Locusts',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 666,
    affixName: 'Primalist Attack and Cast Speed for Summoned Vines',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 737,
    affixName: 'Primalist Chance to Gain Additional Storm Stack',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 335,
    affixName: 'Primalist Cooldown Recovery Speed While Transformed',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 338,
    affixName: 'Primalist Criti Multi While Transformed',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 667,
    affixName: 'Primalist Critical Strike Chance with Rampage',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 351,
    affixName: 'Primalist Damage Over Time While Transformed',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 354,
    affixName: 'Primalist Increased Aspect Of The Boar Duration',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 356,
    affixName: 'Primalist Increased Aspect Of The Lynx Effect',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 353,
    affixName: 'Primalist Increased Aspect Of The Shark Effect',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 355,
    affixName: 'Primalist Increased Aspect Of The Viper Effect',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 352,
    affixName: 'Primalist Increased Totem Crit Chance ',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 357,
    affixName: 'Primalist Increased Totem Damage',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 349,
    affixName: 'Primalist Melee Damage While Transformed',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 347,
    affixName: 'Primalist Minion Chance to Inflict Bleed On Hit',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 336,
    affixName: 'Primalist Minion Crit Multiplier',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 348,
    affixName: 'Primalist Minion Melee Crit Chance',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 346,
    affixName: 'Primalist Minion Melee Leech',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 337,
    affixName: 'Primalist Minion Spell Crit Chance',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 350,
    affixName: 'Primalist Spell Damage While Transformed',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 648,
    affixName: 'Primalist Storm Crow Added Spell Damage',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 334,
    affixName: 'Primalist Totem Added Spell Damage',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 342,
    affixName: 'Primalist Totem Increased Cast Speed',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 665,
    affixName: 'Primalist Upheaval Shockwave Chance',
    structuralCategory: 'class_gated',
    validClasses: ['primalist'],
  },
  {
    affixId: 457,
    affixName: 'Rogue Added Physical Throwing Damage while dual wielding',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 479,
    affixName: 'Rogue Armor Shred Effect',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 451,
    affixName: 'Rogue Bleed Chance per Equipped Sword',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 517,
    affixName: 'Rogue Bleed Chance with Shurikens',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 483,
    affixName: 'Rogue Chance to Ignite on Bow Hit',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 494,
    affixName: 'Rogue Chance to Inflict Bleed on Bow Hit',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 477,
    affixName: 'Rogue Chance to Shred Armor on Bow Hit',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 475,
    affixName: 'Rogue Chance to Shred Armor on Melee Hit',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 473,
    affixName: 'Rogue Chance to Shred Armor on Throwing Hit',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 485,
    affixName: 'Rogue Chance to Slow on Bow Hit',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 449,
    affixName: 'Rogue Chance to gain Dusk Shroud When Hit',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 443,
    affixName: 'Rogue Crimson Shroud Chance on Melee Hit',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 442,
    affixName: 'Rogue Dodge Rating if Hit Recently',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 454,
    affixName: 'Rogue Dusk Shroud Chance on Melee Hit',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 468,
    affixName: 'Rogue Fire Penetration With Ignite',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 440,
    affixName: 'Rogue Health Gained on Glancing Blow',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 521,
    affixName: 'Rogue Increased Acid Flask Area',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 496,
    affixName: 'Rogue Increased Area with Cinder Strike\'s First Strike',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 509,
    affixName: 'Rogue Increased Area with Detonating Arrow',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 481,
    affixName: 'Rogue Increased Armor Shred Duration',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 489,
    affixName: 'Rogue Increased Bow Elemental Damage',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 448,
    affixName: 'Rogue Increased Critical Strike Chance per Equipped Dagger',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 446,
    affixName: 'Rogue Increased Critical Strike Chance per Equipped Sword',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 439,
    affixName: 'Rogue Increased Damage of Shadows',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 524,
    affixName: 'Rogue Increased Dancing Strikes Area',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 513,
    affixName: 'Rogue Increased Hail of Arrows Duration',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 469,
    affixName: 'Rogue Increased Poison Duration',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 471,
    affixName: 'Rogue Increased Throwing Physical Damage',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 498,
    affixName: 'Rogue Increased crit chance with Flurry',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 515,
    affixName: 'Rogue Increased damage per active Shadow with Shadow Cascade',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 511,
    affixName: 'Rogue Increased damage per arrow with Multishot',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 463,
    affixName: 'Rogue Increased damage while wielding a bow',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 461,
    affixName: 'Rogue Increased damage while wielding a dagger',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 459,
    affixName: 'Rogue Increased damage while wielding a sword',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 528,
    affixName: 'Rogue Mana efficiency with Decoy',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 526,
    affixName: 'Rogue Mana efficiency with Synchronised Strike',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 487,
    affixName: 'Rogue Physical Penetration With Shadow Daggers',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 500,
    affixName: 'Rogue Physical penetration with Puncture',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 453,
    affixName: 'Rogue Poison Chance per Equipped Dagger',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 762,
    affixName: 'Rogue Recurve Chance with Heartseeker',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 437,
    affixName: 'Rogue Ward Gained when you create a Shadow',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 532,
    affixName: 'Rogue Ward gained on use with Shift',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 530,
    affixName: 'Rogue Ward gained on use with Smoke Bomb',
    structuralCategory: 'class_gated',
    validClasses: ['rogue'],
  },
  {
    affixId: 655,
    affixName: 'Sentinel Added Lightning Throwing Damage with Javelin',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 370,
    affixName: 'Sentinel Armor Shred Effect',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 764,
    affixName: 'Sentinel Chance To Electrify with Lightning Skills',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 765,
    affixName: 'Sentinel Chance To Inflict Time Rot on hit with Void Skills',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 363,
    affixName: 'Sentinel Chance to Inflict Bleed If Wielding An Axe',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 656,
    affixName: 'Sentinel Endurance While Warpathing',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 374,
    affixName: 'Sentinel Increased Abyssal Decay Duration',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 373,
    affixName: 'Sentinel Increased Echo Damage When A Skill Echoes',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 371,
    affixName: 'Sentinel Increased Fire Damage Over Time',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 378,
    affixName: 'Sentinel Increased Hammer Throw Damage',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 379,
    affixName: 'Sentinel Increased Shield Throw Crit Chance',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 380,
    affixName: 'Sentinel Increased Smelters Wrath Damage',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 368,
    affixName: 'Sentinel Increased Throwing Attack Crit Chance',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 372,
    affixName: 'Sentinel Increased Void Damage Over Time',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 376,
    affixName: 'Sentinel Mana Gained On Rive Hit',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 377,
    affixName: 'Sentinel Mana Gained On Smite Use',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 375,
    affixName: 'Sentinel Mana Gained On Vengeance Hit',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 364,
    affixName: 'Sentinel Melee Physical Damage If Wielding A Mace',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 359,
    affixName: 'Sentinel Melee Physical Damage If Wielding A Sword',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 366,
    affixName: 'Sentinel Necrotic Damage Taken As Physical',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 358,
    affixName: 'Sentinel Physical Penetration With Bleed',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 367,
    affixName: 'Sentinel Poison Damage Taken As Physical',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 369,
    affixName: 'Sentinel Reduced Channel Cost',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 365,
    affixName: 'Sentinel Void Damage Taken As Physical',
    structuralCategory: 'class_gated',
    validClasses: ['sentinel'],
  },
  {
    affixId: 501,
    affixName: 'Strength',
    structuralCategory: 'class_gated',
    validClasses: ['primalist', 'sentinel'],
  },
  {
    affixId: 66,
    affixName: 'Ward On Potion Use',
    structuralCategory: 'class_gated',
    validClasses: ['mage', 'acolyte', 'rogue'],
  },
  {
    affixId: 382,
    affixName: 'Ward Per Second',
    structuralCategory: 'class_gated',
    validClasses: ['mage', 'acolyte'],
  },

  // ── Mastery Signatures ──────────────────────────────────

  {
    affixId: 433,
    affixName: 'Added Bow Physical Damage',
    structuralCategory: 'mastery_signature',
    signatureMasteries: ['marksman', 'falconer'],
  },
  {
    affixId: 432,
    affixName: 'Increased Bow Attack Speed',
    structuralCategory: 'mastery_signature',
    signatureMasteries: ['marksman', 'falconer'],
  },
  {
    affixId: 431,
    affixName: 'Increased Bow Damage',
    structuralCategory: 'mastery_signature',
    signatureMasteries: ['marksman', 'falconer'],
  },
  {
    affixId: 352,
    affixName: 'Primalist Increased Totem Crit Chance ',
    structuralCategory: 'mastery_signature',
    signatureMasteries: ['shaman'],
  },
  {
    affixId: 357,
    affixName: 'Primalist Increased Totem Damage',
    structuralCategory: 'mastery_signature',
    signatureMasteries: ['shaman'],
  },
  {
    affixId: 334,
    affixName: 'Primalist Totem Added Spell Damage',
    structuralCategory: 'mastery_signature',
    signatureMasteries: ['shaman'],
  },
  {
    affixId: 342,
    affixName: 'Primalist Totem Increased Cast Speed',
    structuralCategory: 'mastery_signature',
    signatureMasteries: ['shaman'],
  },
  {
    affixId: 471,
    affixName: 'Rogue Increased Throwing Physical Damage',
    structuralCategory: 'mastery_signature',
    signatureMasteries: ['bladedancer'],
  },
] as const;

// ─────────────────────────────────────────────
// Index maps for fast lookup
// ─────────────────────────────────────────────

export const TAXONOMY_BY_ID: ReadonlyMap<number, AffixTaxonomyEntry> = new Map(
  AFFIX_TAXONOMY.map(e => [e.affixId, e])
);

export function getStructuralCategory(affixId: number): AffixStructuralCategory | undefined {
  return TAXONOMY_BY_ID.get(affixId)?.structuralCategory;
}

export function isClassGated(affixId: number): boolean {
  return TAXONOMY_BY_ID.get(affixId)?.structuralCategory === 'class_gated';
}

export function isValidForClass(affixId: number, baseClass: BaseClass): boolean {
  const entry = TAXONOMY_BY_ID.get(affixId);
  if (!entry?.validClasses) return true; // not class-gated, valid for everyone
  return (entry.validClasses as readonly string[]).includes(baseClass);
}

export function isAttackOnly(affixId: number): boolean {
  return TAXONOMY_BY_ID.get(affixId)?.structuralCategory === 'attack_only';
}

export function isSpellOnly(affixId: number): boolean {
  return TAXONOMY_BY_ID.get(affixId)?.structuralCategory === 'spell_only';
}

export function isMinionOnly(affixId: number): boolean {
  return TAXONOMY_BY_ID.get(affixId)?.structuralCategory === 'minion_only';
}

export function getUniversalDefensiveAffixes(): readonly AffixTaxonomyEntry[] {
  return AFFIX_TAXONOMY.filter(e => e.structuralCategory === 'universal_defensive');
}
