/**
 * affix-overrides.ts
 * Manual classification for affixes whose damage-type relevance
 * cannot be reliably inferred from their name alone.
 *
 * This file is authored by hand and reviewed carefully.
 * The programmatic classifier handles obvious cases (affixes with
 * "cold", "fire", "void" etc. in their name). This file handles
 * the ambiguous ~30-50 affixes where name-matching would fail or
 * produce wrong results.
 *
 * Rules:
 * - Only add entries that the programmatic classifier gets wrong
 * - Always add a `reason` so future maintainers understand the decision
 * - `is_damage_locked: true` means ONLY relevant to builds with this damage type
 * - `is_damage_locked: false` means relevant to this type but not exclusively
 */

import type { DamageType } from './damage-types';

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

export interface AffixClassificationOverride {
  readonly affixId: number;
  readonly affixName: string;  // for human readability only
  readonly isDamageLocked: boolean;
  readonly reason: string;
  readonly author: string;
}

// ─────────────────────────────────────────────
// Overrides
// ─────────────────────────────────────────────

export const AFFIX_CLASSIFICATION_OVERRIDES: readonly AffixClassificationOverride[] = [

  // ── Stat scaling affixes that imply a damage type ──────────────────────
  {
    affixId: 21,
    affixName: 'Primalist Added Spell Damage With Tempest Strike',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 99,
    affixName: 'Ward Gained on Kill',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 216,
    affixName: 'Idol Primalist Bees Per 10 Seconds',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 334,
    affixName: 'Primalist Totem Added Spell Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 335,
    affixName: 'Primalist Cooldown Recovery Speed While Transformed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 336,
    affixName: 'Primalist Minion Crit Multiplier',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 337,
    affixName: 'Primalist Minion Spell Crit Chance',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 338,
    affixName: 'Primalist Criti Multi While Transformed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 339,
    affixName: 'Mage Cold Penetration With Frostbite',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 342,
    affixName: 'Primalist Totem Increased Cast Speed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 346,
    affixName: 'Primalist Minion Melee Leech',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 347,
    affixName: 'Primalist Minion Chance to Inflict Bleed On Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 348,
    affixName: 'Primalist Minion Melee Crit Chance',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 349,
    affixName: 'Primalist Melee Damage While Transformed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 350,
    affixName: 'Primalist Spell Damage While Transformed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 351,
    affixName: 'Primalist Damage Over Time While Transformed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 352,
    affixName: 'Primalist Increased Totem Crit Chance ',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 353,
    affixName: 'Primalist Increased Aspect Of The Shark Effect',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 354,
    affixName: 'Primalist Increased Aspect Of The Boar Duration',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 355,
    affixName: 'Primalist Increased Aspect Of The Viper Effect',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 356,
    affixName: 'Primalist Increased Aspect Of The Lynx Effect',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 357,
    affixName: 'Primalist Increased Totem Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 358,
    affixName: 'Sentinel Physical Penetration With Bleed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 359,
    affixName: 'Sentinel Melee Physical Damage If Wielding A Sword',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 363,
    affixName: 'Sentinel Chance to Inflict Bleed If Wielding An Axe',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 364,
    affixName: 'Sentinel Melee Physical Damage If Wielding A Mace',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 365,
    affixName: 'Sentinel Void Damage Taken As Physical',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 366,
    affixName: 'Sentinel Necrotic Damage Taken As Physical',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 367,
    affixName: 'Sentinel Poison Damage Taken As Physical',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 368,
    affixName: 'Sentinel Increased Throwing Attack Crit Chance',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 369,
    affixName: 'Sentinel Reduced Channel Cost',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 370,
    affixName: 'Sentinel Armor Shred Effect',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 371,
    affixName: 'Sentinel Increased Fire Damage Over Time',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 372,
    affixName: 'Sentinel Increased Void Damage Over Time',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 373,
    affixName: 'Sentinel Increased Echo Damage When A Skill Echoes',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 374,
    affixName: 'Sentinel Increased Abyssal Decay Duration',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 375,
    affixName: 'Sentinel Mana Gained On Vengeance Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 376,
    affixName: 'Sentinel Mana Gained On Rive Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 377,
    affixName: 'Sentinel Mana Gained On Smite Use',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 378,
    affixName: 'Sentinel Increased Hammer Throw Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 379,
    affixName: 'Sentinel Increased Shield Throw Crit Chance',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 380,
    affixName: 'Sentinel Increased Smelters Wrath Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 381,
    affixName: 'Mage Spell Crit Doubled Over 300 Max Mana',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 383,
    affixName: 'Mage Added Spell Damage While Channelling',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 384,
    affixName: 'Acolyte Minion Freeze Rate',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 385,
    affixName: 'Mage Lightning Crit Multi',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 386,
    affixName: 'Mage Spell Damage Leeched While Channelling',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 387,
    affixName: 'Mage Chance To Apply Frostbite With Cold Skills',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 388,
    affixName: 'Mage Increased Cold Damage Over Time',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 389,
    affixName: 'Mage Increased Fire Damage Over Time',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 390,
    affixName: 'Mage Increased Melee Elemental Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 391,
    affixName: 'Mage Chance To Ignite With Fire Skills',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 392,
    affixName: 'Mage Chance To Shock With Lightning Skills',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 393,
    affixName: 'Mage Chance To Cast Fire Aura On Crit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 394,
    affixName: 'Mage Increased Fire Aura Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 395,
    affixName: 'Mage Chance To Gain Lightning Aegis When Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 396,
    affixName: 'Mage Chance To Cast Fire Aura When Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 398,
    affixName: 'Mage Chance To Cast Fire Aura On Kill With A Fire Skill',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 399,
    affixName: 'Mage Chance to Apply a Spark Charge on Melee Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 400,
    affixName: 'Mage Mana Spent Gained as Ward',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 401,
    affixName: 'Acolyte Physical Damage While Transformed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 402,
    affixName: 'Acolyte Necrotic Damage While Transformed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 410,
    affixName: 'Acolyte Increased Skeletal Mage Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 411,
    affixName: 'Acolyte Mana Gained On Harvest Use',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 412,
    affixName: 'Acolyte Leech With Harvest',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 413,
    affixName: 'Acolyte Minion Reflect',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 415,
    affixName: 'Acolyte Chance To Gain 20 Ward On Kill With Hungering Souls',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 420,
    affixName: 'Acolyte Spell Damage Per Skeletal Mage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 421,
    affixName: 'Acolyte Chance To Apply Damned On Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 422,
    affixName: 'Acolyte Damage Leeched As Health While Transformed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 423,
    affixName: 'Acolyte Reduced Health Cost Of Spells',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 424,
    affixName: 'Acolyte Physical Spell Critical Strike Chance',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 435,
    affixName: 'Acolyte Chance To Cast Marrow Shards When You Cast Transplant',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 437,
    affixName: 'Rogue Ward Gained when you create a Shadow',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 439,
    affixName: 'Rogue Increased Damage of Shadows',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 440,
    affixName: 'Rogue Health Gained on Glancing Blow',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 442,
    affixName: 'Rogue Dodge Rating if Hit Recently',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 443,
    affixName: 'Rogue Crimson Shroud Chance on Melee Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 446,
    affixName: 'Rogue Increased Critical Strike Chance per Equipped Sword',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 448,
    affixName: 'Rogue Increased Critical Strike Chance per Equipped Dagger',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 449,
    affixName: 'Rogue Chance to gain Dusk Shroud When Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 451,
    affixName: 'Rogue Bleed Chance per Equipped Sword',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 453,
    affixName: 'Rogue Poison Chance per Equipped Dagger',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 454,
    affixName: 'Rogue Dusk Shroud Chance on Melee Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 457,
    affixName: 'Rogue Added Physical Throwing Damage while dual wielding',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 459,
    affixName: 'Rogue Increased damage while wielding a sword',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 461,
    affixName: 'Rogue Increased damage while wielding a dagger',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 463,
    affixName: 'Rogue Increased damage while wielding a bow',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 468,
    affixName: 'Rogue Fire Penetration With Ignite',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 469,
    affixName: 'Rogue Increased Poison Duration',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 471,
    affixName: 'Rogue Increased Throwing Physical Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 473,
    affixName: 'Rogue Chance to Shred Armor on Throwing Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 475,
    affixName: 'Rogue Chance to Shred Armor on Melee Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 477,
    affixName: 'Rogue Chance to Shred Armor on Bow Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 479,
    affixName: 'Rogue Armor Shred Effect',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 481,
    affixName: 'Rogue Increased Armor Shred Duration',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 483,
    affixName: 'Rogue Chance to Ignite on Bow Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 485,
    affixName: 'Rogue Chance to Slow on Bow Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 487,
    affixName: 'Rogue Physical Penetration With Shadow Daggers',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 489,
    affixName: 'Rogue Increased Bow Elemental Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 494,
    affixName: 'Rogue Chance to Inflict Bleed on Bow Hit',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 496,
    affixName: "Rogue Increased Area with Cinder Strike's First Strike",
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 498,
    affixName: 'Rogue Increased crit chance with Flurry',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 500,
    affixName: 'Rogue Physical penetration with Puncture',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 509,
    affixName: 'Rogue Increased Area with Detonating Arrow',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 511,
    affixName: 'Rogue Increased damage per arrow with Multishot',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 513,
    affixName: 'Rogue Increased Hail of Arrows Duration',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 515,
    affixName: 'Rogue Increased damage per active Shadow with Shadow Cascade',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 517,
    affixName: 'Rogue Bleed Chance with Shurikens',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 521,
    affixName: 'Rogue Increased Acid Flask Area',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 522,
    affixName: 'Idol Rogue Chance to Summon A Bee with Acid Flask',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 524,
    affixName: 'Rogue Increased Dancing Strikes Area',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 526,
    affixName: 'Rogue Mana efficiency with Synchronised Strike',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 528,
    affixName: 'Rogue Mana efficiency with Decoy',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 530,
    affixName: 'Rogue Ward gained on use with Smoke Bomb',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 532,
    affixName: 'Rogue Ward gained on use with Shift',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 648,
    affixName: 'Primalist Storm Crow Added Spell Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 655,
    affixName: 'Sentinel Added Lightning Throwing Damage with Javelin',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 656,
    affixName: 'Sentinel Endurance While Warpathing',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 663,
    affixName: 'Primalist Armor Shred Chance for Locusts',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 665,
    affixName: 'Primalist Upheaval Shockwave Chance',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 666,
    affixName: 'Primalist Attack and Cast Speed for Summoned Vines',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 667,
    affixName: 'Primalist Critical Strike Chance with Rampage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 685,
    affixName: 'Idol Mage Elemental Bees Per 10 Seconds',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 687,
    affixName: 'Mage Ward per Second on Glyph of Dominion',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 688,
    affixName: 'Mage Flame Rush Speed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 690,
    affixName: 'Mage Mana on Runebolt or Fireball Cast',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 691,
    affixName: 'Mage Ward per Rune consumed with Runic Invocation',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 737,
    affixName: 'Primalist Chance to Gain Additional Storm Stack',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 747,
    affixName: 'Acolyte Additional Projectile Chance with Chaos Bolts',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 748,
    affixName: 'Acolyte Increased Spirit Frequency with Chthonic Fissure',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 749,
    affixName: 'Acolyte Added Spell Damage for Curses',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 762,
    affixName: 'Rogue Recurve Chance with Heartseeker',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 764,
    affixName: 'Sentinel Chance To Electrify with Lightning Skills',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 765,
    affixName: 'Sentinel Chance To Inflict Time Rot on hit with Void Skills',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 36,
    affixName: 'Hybrid Health',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 332,
    affixName: 'Primalist Armor And Minion Armor',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 333,
    affixName: 'Primalist Shared Lightning Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 340,
    affixName: 'Primalist Shared Cold Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 343,
    affixName: 'Primalist Shared Bleed Duration',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 344,
    affixName: 'Primalist Shared Increased Spell Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 345,
    affixName: 'Primalist Shared Increased Melee Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 360,
    affixName: 'Sentinel Increased Physical Damage And Bleed Duration',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 361,
    affixName: 'Sentinel Increased Fire Damage And Ignite Duration',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 362,
    affixName: 'Sentinel Increased Void Damage And Added Spell Void Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 397,
    affixName: 'Flame Ward Charge and Added Ward',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 404,
    affixName: 'Acolyte Shared Increased Fire Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 405,
    affixName: 'Acolyte Shared Increased Necrotic Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 406,
    affixName: 'Acolyte Shared Bleed Chance',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 407,
    affixName: 'Acolyte Shared Increased Bleed Duration',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 408,
    affixName: 'Acolyte Shared Physical Penetration With Bleed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 409,
    affixName: 'Acolyte Shared Physical Leech',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 414,
    affixName: 'Acolyte Poison Damage And Poison Resistance',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 416,
    affixName: 'Acolyte Shared Increased Crit Chance',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 417,
    affixName: 'Acolyte Increased Projectile Speed With Marrow Shards And Bone Nova',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 418,
    affixName: 'Acolyte Increased Damage With Rip Blood And Blood Splatter',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 419,
    affixName: 'Acolyte Critical Strike Chance For Skeletons And Skeletal Mages',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 192,
    affixName: 'Acolyte +1 Skeleton and Increased Skeleton Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 534,
    affixName: 'Rogue Black Arrows dropped by Dark Quiver and Increased Bow Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 536,
    affixName: 'Rogue Max Ballista and Increased Ballista Attack Speed',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 537,
    affixName: 'Rogue Mirages and Mana Efficiency with Lethal Mirage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 548,
    affixName: 'Mage Fireball Pierce Chance',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 649,
    affixName: 'Acolyte Volatile Zombie Speed and Damage',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 519,
    affixName: 'Rogue Lightning Damage with Shurikens',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 693,
    affixName: 'Mage Penetration with Fire Invocations',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 694,
    affixName: 'Mage Penetration with Cold Invocations',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 695,
    affixName: 'Mage Frost Wall Duration and Frostbite Chance',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 696,
    affixName: 'Mage Penetration with Lightning Invocations',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 739,
    affixName: 'Rogue Damage and Area with Dive Bomb',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },
  {
    affixId: 825,
    affixName: 'Added Health and Added Health Regeneration',
    isDamageLocked: false,
    reason: 'Rare affix',
    author: 'marc-antoine',
  },

] as const;

// ─────────────────────────────────────────────
// Registry helpers
// ─────────────────────────────────────────────

export const OVERRIDE_MAP: ReadonlyMap<number, AffixClassificationOverride> = new Map(
  AFFIX_CLASSIFICATION_OVERRIDES.map(o => [o.affixId, o])
);

export function getOverride(affixId: number): AffixClassificationOverride | undefined {
  return OVERRIDE_MAP.get(affixId);
}

export function hasOverride(affixId: number): boolean {
  return OVERRIDE_MAP.has(affixId);
}
